CREATE TABLE `finance` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `uid` int(11) unsigned NOT NULL COMMENT '用户id',
  `account_no` varchar(40) NOT NULL COMMENT '账户编号',
  `account_kind` varchar(40) NOT NULL COMMENT '账户类型：主，子帐户，借贷帐户等',
  `asset_code` varchar(40) NOT NULL COMMENT '资产代码',
  `amount_available` decimal(32,8) NOT NULL DEFAULT '0.00000000' COMMENT '可用金额',
  `amount_lock` decimal(32,8) NOT NULL DEFAULT '0.00000000' COMMENT '冻结金额',
  `amount_sum` decimal(32,8) NOT NULL DEFAULT '0.00000000' COMMENT '总金额(开始到现在的金额)',
  `amount_remaining` decimal(32,8) NOT NULL DEFAULT '0.00000000' COMMENT '剩余金额(可用+冻结)',
  `use_percent` decimal(32,8) NOT NULL DEFAULT '0.00000000' COMMENT '用电额度',
  `version` int(11) DEFAULT '0' COMMENT '版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uid_asset_code` (`uid`,`asset_code`),
  KEY `idx_finance_deleted_at` (`deleted_at`),
  KEY `idx_asset_code` (`asset_code`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COMMENT='用户资产表';
